name: Testing API
on:
  push:
  pull_request:
jobs:
  testing-api:
    runs-on: ubuntu-latest
    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: env  # Nombre de tu entorno Conda
      - name: Installing dependencies
        run: |
          pip install dvc[gs]
          pip install -r requirements.txt
      - name: Testing API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-tracker
          pytest test.py

