name: Testing API

on: [push, pull_request]

jobs:
  testing-api:
    runs-on: ubuntu-latest

    env:
      SERVICE_ACCOUNT_KEY: ${{ secrets.SERVICE_ACCOUNT_KEY }}

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Setup Conda environment
        run: |
          conda create --name env python=3.8 -y
          source activate env

      - name: Installing dependencies
        run: |
          pip install -r requirements_test.txt

      - name: Test API
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$(python utilities/setter.py)
          dvc pull model/model.pkl -r model-tracker
          pytest tests.py
